name: First Workflow
on: worflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "I'm sleepy"
      - name: Print goodbye
        run: "I'm getting a beef pattie after this done"
