name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "I'm sleepy"
      - name: Print goodbye
        run: echo "I need a beef pattie"
